In [52]:
import pandas as pd

df = pd.read_csv("C:\\Users\\孔德舜\\PycharmProjects\\AIProject\\robots\\csv_data\\movie_list.csv")

# 配置项，用于展示所有的数据
# pd.set_option('display.max_rows', None)
# df


# 数据处理
df['有效时长'] = df['时长'] - 20

# 写入数据
df.to_csv("data/movies_list_02.csv",index=False)

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述
0,蝙蝠俠 騎士殞落（一）：騎士殞落,2026,2026/08/25,"动画,动作,冒险,科幻",79,92,英語,比爾·芬格,鮑勃·凱恩,概覽,"Arkham Asylum has been destroyed, and all its ..."
1,Avatar Aang: The Last Airbender,2026,2026/07/24,"动画,冒险,奇幻,动作",99,91,-,Tim Hedrick,勞倫·蒙哥馬利,The legacy reawakens.,"Avatar Aang, the world's last Airbender, learn..."
2,奇幻變身大冒險,2026,2026/05/01,"冒险,动画,家庭,奇幻",102,89,英語,內森·格雷諾,Robert Snow,Transform your destiny.,林地小動物和大鳥突然互換了身體，只好彼此合作，共同面對一生最瘋狂的冒險。
3,Accidental Partners,2026,2026/03/12,"喜剧,爱情",110,88,西班牙語,Ihtzi Hurtado,Miguel García Moreno,概覽,Two women discover they were both scammed by t...
4,鬼滅之刃劇場版 無限城篇 第一章 猗窩座再襲,2025,2025/08/14,"动画,动作,奇幻",155,88,日語,外崎春雄,吾峠呼世晴,It's time to have some fun.,為了讓變成鬼的妹妹禰豆子變回人類，加入鬼殺隊的灶門炭治郎，一路上與不同的「柱」成為同伴，並肩...
5,夜巡毒梟,2026,2026/08/21,"犯罪,动作,惊悚",91,88,西班牙語,Chava Cartas,Bernardo Esquinca,概覽,兩位墨西哥員警不幸得罪一名殘忍的毒梟後，必須拼命撐過值勤的最後幾小時。這部犯罪劇情片改編自真...
6,月黑高飛,1994,1995/10/26,"剧情,犯罪",142,87,英語,法蘭·達拉本特,史提芬·京,Fear can hold you prisoner. Hope can set you f...,1947 年，一位年輕的波特蘭銀行家安迪·杜佛蘭（添·羅賓斯飾）被指控殺死其妻子與其情夫，分...
7,教父,1972,1980/01/24,"剧情,犯罪",175,87,英語,法蘭西斯·柯波拉,馬里奧·普佐,An offer you can't refuse.,電影描述西西里的柯里安大家族於美國掘起，辛苦掙扎奮鬥成為黑幫教父，最後引起權力鬥爭，甚至家族...
8,末日聖母號,2026,2026/03/19,"科幻,冒险",157,86,英語,菲力洛迪文,克里斯·米勒,Believe in the Hail Mary.,科學老師 Ryland Grace（賴恩高斯寧 飾）在一艘距離地球數光年遠的太空船上醒來，隨...
9,米高積遜,2026,2026/04/22,"音乐,剧情",128,86,英語,安東尼·福奎阿,約翰·洛根,Discover the making of a king.,《米高積遜》聚焦他的音樂成就，更深入描寫他舞台之外的人生軌跡：從幼年被發掘成為 Jackso...
10,年少心事,2024,2024/09/14,"剧情,爱情",99,86,荷蘭語,安東尼·沙特曼,NaN,概覽,在學期間，13 歲的 Elias 與來自布魯塞爾的 14 歲新鄰居 Alexander 成為...
11,教父續集,1974,1974/12/20,"剧情,犯罪",200,86,英語,法蘭西斯·柯波拉,馬里奧·普佐,The rise and fall of the Corleone empire.,柯裏安家族幼子米高（阿爾柏仙奴飾）自繼承大權後，續漸將勢力滲入各正當企業及政治圈中，企圖將黑...
12,十二怒漢,1957,1957/04/10,剧情,97,86,英語,雷金納德·羅斯,西德尼·盧梅特,It explodes like 12 sticks of dynamite!,本片所有場景幾乎都發生在一個小房間內，講述 11 名陪審團如何在另一名持反對意見的陪審團的説...
13,舒特拉的名單,1993,1994/03/17,"剧情,历史,战争",195,86,英語,史提芬·史匹堡,湯瑪斯·簡尼利,"Whoever saves one life, saves the world entire.",電影情節於 1939 年德國發起的猶太大移民開始。那時二戰剛剛打響，克拉科夫周圍的波蘭猶太人...
14,鏈鋸人 - 劇場版：蕾潔篇,2025,2025/09/25,"动画,动作,爱情,奇幻",100,86,日語,吉原達矢,瀨古浩司,"Lost Love, Flower, Chainsaw.",主角澱治曾是黑幫的惡魔獵人，試圖償還父母留下的債務。後來，他被黑幫背叛、殺害，就在瀕死之際，...
15,蝙蝠俠—黑夜之神,2008,2008/07/17,"动作,惊悚,犯罪",152,85,英語,基斯杜化·路蘭,鮑勃·凱恩,俠影出洞 迎戰無法無天,在警長佔哥頓和新檢察官哈菲丹特的幫助下，蝙蝠俠主動出擊，搗破葛鹹城中的邪惡勢力。這個伸張正義...
16,千與千尋,2001,2001/12/13,"动画,家庭,奇幻",125,85,日語,宮崎駿,NaN,Beyond the tunnel was a mysterious town.,某一天，年僅 10 歲的荻野千尋跟著父母坐在車上，準備一同前往要搬入的新家。在路途當中，千尋...
17,綠里奇蹟,1999,2000/03/09,"奇幻,剧情,犯罪",189,85,英語,法蘭·達拉本特,史提芬·京,Paul Edgecomb didn't believe in miracles. Unti...,所謂「綠裏」，是指從監房到死囚之間地面上塗上綠色油漆的路程，獄長保甸多年來曾送過不少死囚走過...
18,魔戒三部曲：王者再臨,2003,2003/12/18,"冒险,奇幻,动作",251,85,英語,彼得積遜,J·R·R·託爾金,There can be no triumph without loss. No victo...,遠征隊還是分頭努力，一邊是亞拉岡、勒苟拉斯、金霹加上洛汗國的希優頓；另一頭則有梅裏、皮聘見證...
19,漂洋過海愛上你,1995,1995/10/20,"喜剧,剧情,爱情",190,85,印地語,Aditya Chopra,NaN,"Come… fall In love, all over again…",當拉傑（沙魯克罕飾）與希姆蘭（卡約兒飾）首次在歐洲的鐵路假日行相遇時，並未徹底一見鍾情。但是...
20,上流寄生族,2019,2019/06/20,"喜剧,惊悚,剧情",132,85,韓語,奉俊昊,韓進元,Act like you own the place.,窮爸爸基澤 (宋康昊 飾) 一家四口全是無業遊民，他們終日望天打卦，直至長子基佑 (崔宇植 ...
21,星際啟示錄,2014,2014/11/06,"冒险,剧情,科幻",169,85,英語,基斯杜化·路蘭,尊納頓路蘭,Mankind was born on Earth. It was never meant ...,世界在歷經極端氣候與糧食危機，地球瀕臨末日之際，一位電機工程師（馬修麥康納希 Matthew...
22,你的名字,2016,2016/11/11,"动画,爱情,剧情",106,85,日語,新海誠,NaN,"Separated by distance, connected by fate.",故事發生在日本千年一遇的流星夜後一個月。住在鄉郊的女高中生宮水三葉對這種生活感到枯燥，一直非...
23,危險人物,1994,1995/03/23,"惊悚,犯罪,喜剧",154,85,英語,昆頓·塔倫天奴,羅傑·阿瓦里,You won’t know the facts until you’ve seen the...,幾個擦身而過的人，在黑道世界中交織出微妙錯綜的故事。
24,獨行俠決鬥地獄門,1966,1968/06/13,西部,161,85,意大利語,賽爾喬·萊昂內,盧西亞諾·文森佐尼,For three men the Civil War wasn't hell. It wa...,美國南北戰爭時期，南方政府埋藏了一批黃金。這個消息恰好被三名主角知道了，然而他們每個人只知道...
25,切腹,1962,1962/09/15,"动作,剧情,历史",135,85,-,小林正樹,瀧口康彥,"What befalls others today, may be your own fat...",影片根據瀧口康彥的小説《異聞浪人記》改編，圍繞展現武士道精神的終極形式——切腹展開了一個別開...
26,阿甘正傳,1994,1994/12/15,"喜剧,剧情,爱情",142,85,英語,羅伯特·澤米吉斯,温斯頓·格魯姆,The world will never be the same once you've s...,阿甘自幼與母親相依為命，雖然智商比普通人為低，雙腳亦天生有障礙。但他生性篤實，與世無爭，在母...
27,Selena Gomez：聽聽，最真的我,2022,2022/11/04,"纪录,音乐",95,85,英語,阿萊克·凱西西恩,Paul Marchand,把握時時刻刻，衝破人生幽谷。,受公眾關注多年，Selena Gomez大紅大紫，但正當她要再創高峰時，一個意外轉折把她拉進...
28,盜亦有道,1990,1990/11/01,"剧情,犯罪",145,85,英語,馬田史高西斯,尼古拉斯·皮萊吉,Three decades of life in the mafia.,亨利生長在 20 世紀 50 年代美國紐約市東的布魯克林區，他很小時就開始注意到街口對面的意...
29,七俠四義,1954,1954/04/26,"动作,剧情",207,85,日語,黑澤明,橋本忍,Unmatched for suspense and spectacle!,日本戰國時代末期，不少武士淪落為作惡多端的山賊。一個村莊的村民，經常遭受野武士搶劫，無意又得...
30,¿Quieres ser mi hijo?,2023,2023/09/21,"喜剧,爱情",100,85,-,Ihtzi Hurtado,NaN,概覽,"Lu, a conformist woman in her forties, learns ..."
31,再見螢火蟲,1988,1988/04/16,"动画,剧情,战争",89,85,日語,高畑勳,NaN,Why do fireflies have to die so soon?,美日戰爭爆發，14 歲的清太帶著年幼的妹妹到處逃命，當他們到達防空洞的時候，母親已身受重傷，...
32,魔戒首部曲：魔戒現身,2001,2002/01/31,"冒险,奇幻,动作",208,84,英語,彼得積遜,J·R·R·託爾金,One ring to rule them all.,黑暗魔王索倫鑄造了一隻至尊魔戒，神奇力量足以令他征服眾生靈，輾轉被哈比族人佛羅多巴金斯所承繼...
33,David Attenborough：活在天與地,2020,2020/09/28,"纪录,剧情",83,84,英語,Keith Scholey,艾雷斯泰·法瑟吉爾,概覽,節目主持人講述自己的人生，並回顧地球上的生命演化史，以此悼念消逝的野生棲地，同時分享他對未來...
34,搏擊會,1999,1999/11/11,"剧情,惊悚",139,84,英語,大衞·芬查,恰克·帕拉尼克,Mischief. Mayhem. Soap.,愛德華諾頓飾演一位失眠病患者，讀完大學，找到一份工作，然後買屋，過著沉悶痛苦的刻板生活。直到...
35,一個快樂的傳説,1997,1997/12/20,"喜剧,剧情",116,84,意大利語,羅貝託·貝尼尼,文森佐·塞拉米,殘酷戰火下 以頑抗宿命 以歡笑活出傳說,圭多是一個心地善良樂觀的猶太青年。他對生活充滿了美好的嚮往。他和好友駕駛破車從鄉間來到阿雷佐...
36,星光伴我心,1988,1990/01/18,"剧情,爱情",124,84,意大利語,基斯比·湯納度,NaN,An enchanted village. A wonderful friendship. ...,義大利小男孩多多喜愛電影，在 Cinema Paradiso 戲院流聯忘返。他在戲院跟亦師亦...
37,每個人的每件事,2019,2019/03/10,纪录,115,84,英語,Sebastian Jones,Ramez Silyan,概覽,本紀錄片近距離刻畫歌手小皮普的崛起，他的音樂揉合各種風格，吸引大批追隨者，最後也定義了他的人生。
38,人類啟示錄,2015,2015/09/12,纪录,191,84,法語,楊·亞祖－貝彤,NaN,概覽,集攝影師、記者、環保倡議者於一身的全能導演Yann-Arthus Bertrand完成大自然...
39,魔戒二部曲：雙城奇謀,2002,2003/01/09,"冒险,奇幻,动作",223,84,英語,彼得積遜,J·R·R·託爾金,The journey continues.,黑暗魔王索倫鑄造了一隻至尊魔戒，神奇力量足以令他征服眾生靈，輾轉被哈比族人佛羅多巴金斯所承繼...
40,無主之城,2002,2003/05/08,"剧情,犯罪",129,84,葡萄牙語,費蘭度·美拿里斯,保羅·林斯,"If you run, the beast catches you; if you stay...",「天主之城」是最危險的貧民窟，住在這裏的孩子們幾乎人手一槍，進入此區的貨車都難逃被劫的命運，...
41,妙不可言,2021,2021/06/17,"家庭,剧情",88,84,西班牙語,Ernesto Contreras,Estéfani Enríquez Soto,There are encounters that change your life,生活是如此奇妙且難以預測，有時會在最不經意的地方發現幸福：一位七旬老嫗和她的少年鄰居之間產生...
42,明亮燦爛的你,2026,2026/05/08,"剧情,悬疑",114,84,英語,奧利維亞·紐曼,約翰·惠廷頓,Brighter together.,這部動人的劇情片改編自暢銷小說，描述一名寡婦在小鎮水族館值夜班，和一隻聰明的章魚及一個迷茫的...
43,A Dog's Will,2000,2000/09/15,"喜剧,剧情,奇幻,爱情",104,84,葡萄牙語,蓋爾·阿賴斯,Ariano Suassuna,Lying with faith is not always a sin.,The lively João Grilo and the sly Chicó are po...
44,觸目驚心,1960,1961/01/12,"恐怖,惊悚,悬疑",109,84,英語,亞弗列·希治閣,羅伯特·布洛克,A new and altogether different screen excitement!,該片講述了瑪莉蓮在浴室中被精神分裂的狂人殺死，之後瑪莉蓮的姐姐和男友加入警方的調查，在逐步偵...
45,飛越瘋人院,1975,1975/11/19,剧情,135,84,英語,米路士·科曼,肯·克西,"In this clean, orderly, disciplined world, who...",劇本改編自一部同名小説，曾獲 1975 年第 48 屆奧斯卡最佳影片，最佳男、女主角，最佳導...
46,蜘蛛俠：跳入蜘蛛宇宙,2018,2018/12/13,"动画,动作,冒险,科幻",117,84,英語,洛迪文尼·羅斯曼,菲力洛迪文,Enter a universe where more than one wears the...,一個生活在布魯克林的平凡青年麥爾斯 (Miles) 發現自己擁有不尋常力量，徬徨之際，蜘蛛俠...
47,Lucy Shimmers and the Prince of Peace,2020,2020/10/19,"剧情,家庭",87,84,-,Rob Diamond,NaN,概覽,Second chances start when a hardened criminal ...
48,Protector,2026,2026/03/06,"动作,惊悚",90,84,-,阿德裏安·格魯伯格,Mun-Bong Seub,Never get between a mother and her child.,Nikki's life is shattered when her daughter is...
49,羅小黑戰記,2019,2019/08/27,"动画,奇幻,动作,冒险",102,84,漢語,木頭,彭可欣,One Small Spirit Will Determine the Fate of th...,在妖攘的人類世界裏，很多妖精隱瞞其中，他們與人類相安無事地生活著。貓妖羅小黑因為家園被破壞，...
50,電影版 聲之形,2016,2017/04/06,"动画,剧情,爱情",130,84,日語,山田尚子,吉田玲子,Sometimes the answer is as simple as learning ...,最討厭無聊的少年，主角石田將也。小學時曾經是孩子王的他，對弱聽的轉校生．西宮硝子抱有單純的好...
51,希望：為愛重生,2013,2013/10/02,剧情,122,84,韓語,李濬益,曹重勳,We won't let her shed tears again.,8 歲的素媛慘遭殘忍性侵，險些喪命之後，全家人努力扶持她療傷，同時也得應對自己的憤怒與悲痛。
52,星球大戰：帝國反擊戰,1980,1980/08/08,"冒险,动作,科幻",124,84,英語,艾榮·卡舒納,勞倫斯·卡斯丹,The Star Wars saga continues.,帝國軍被擊敗後勃然大怒，派出精鋭部隊追擊盟軍，Han Solo 和公主 Leia 在逃亡到雲...
53,哈爾移動城堡,2004,2005/03/24,"奇幻,动画,冒险",119,84,日語,宮崎駿,戴安娜·韋恩·瓊斯,被魔咒變成九十歲的少女，遇上移動城堡的魔法師,18 歲少女蘇菲被荒野女巫的魔咒變成了 90 歲老婆婆，為找尋解除咒語的方法，偶然闖入了四處...
54,天國與地獄,1963,1963/03/01,"剧情,犯罪,惊悚,悬疑",142,84,日語,黑澤明,埃文·亨特,"Stark, intense drama almost beyond belief!",靠自己努力當上鞋業公司高層的權藤，正為公司的事務發愁，不料他司機的兒子進一卻被綁匪誤當成他的...
55,七宗罪,1995,1995/11/30,"犯罪,悬疑,惊悚",127,84,英語,大衞·芬查,安德魯·凱文·沃克,Gluttony. Greed. Sloth. Envy. Wrath. Pride. Lust.,故事從天主教中有 7 種死罪説起，一場離奇的連環殺人案，受害者都是死於這 7 宗罪其中一種。...
56,加百列的地獄,2020,2020/05/29,"爱情,剧情",122,84,英語,Tosca Musk,Sylvain Reynard,概覽,關於誘惑、禁止的愛情和救贖的有趣探索，一個人試圖掙得不可能的東西：寬恕和愛，這是一個引人入勝...
57,鼓動真我,2014,2014/10/15,"剧情,音乐,惊悚",107,84,英語,戴米恩·查素,NaN,是誰教我完美鼓音 是誰逼我挑戰鼓神 不瘋魔 活不成真我!,受寫作事業失敗的父親影響，19 歲 Andrew（米爾斯泰勒
58,潛行凶間,2010,2010/07/29,"动作,科幻,冒险",148,84,英語,基斯杜化·路蘭,NaN,進入 最危險思維空間 掀動 最奇幻驚世罪幕,Dom Cobb 是一名精於潛盜的神偷，專門趁目標人物於睡夢狀態中思維最軟弱的時候，潛入他們...
59,義薄雲天,1984,1984/08/11,"剧情,犯罪",139,84,英語,賽爾喬·萊昂內,哈里·格雷,"Crime, passion and lust for power.",里昂尼將舞台由西部搬至紐約地下黑幫世界，以幾個猶太裔流氓的一生折射美國夢的陰暗。悠長肅殺的排...
60,鋼琴戰曲,2002,2003/01/24,"剧情,战争",150,84,英語,羅曼·波蘭斯基,羅納德·哈伍德,戰火無情 琴鍵無聲 心靈與天地奏鳴 為時代傷痕作證,1939 年，二戰爆發，當時只得 27 歲的華迪拉史標曼 Wladyslaw Szpilma...
61,反斗奇兵 5,2026,2026/06/18,"动画,家庭,喜剧,冒险",102,84,英語,安德魯·斯坦頓,Kenna Harris,It's on.,一班玩具朋友面對「莉莉平板」（Lily Pad）如臨大敵，嚇到騰騰震，誓要與現今小朋友最沉迷...
62,蜘蛛俠：飛躍蜘蛛宇宙,2023,2023/06/01,"动画,动作,冒险,科幻",140,84,英語,喬伊姆·多斯·桑托斯,賈斯汀·K·湯普森,It's how you wear the mask that matters.,Sony Pictures 榮譽發行、奧斯卡最佳動畫電影《蜘蛛俠：跳入蜘蛛宇宙》最新一章《蜘...
63,沉默的羔羊,1991,1991/05/10,"犯罪,惊悚,剧情",119,83,英語,喬納森·戴米,湯瑪斯·哈里斯,To enter the mind of a killer she must challen...,正在 FBI 受訓的實習探員克麗絲·史達琳，奉局長傑克·克勞福之命，前去探訪醫生漢尼拔·萊克...
64,加百列的地獄 2,2020,2020/07/31,"爱情,剧情",106,83,英語,Tosca Musk,Sylvain Reynard,概覽,加布裏埃爾·愛默生教授終於發現了朱莉婭·米切爾身份的真相，但他的意識到為時已晚。茱莉亞最終希...
65,造反有理,1984,1984/10/19,"纪录,音乐",88,83,英語,喬納森·戴米,NaN,Why stop making sense? Why a movie? Why a big ...,紀錄 Talking Heads 1983 年 12 月宣傳專輯 Speaking in T...
66,魷魚遊戲：第 2 季：製作特輯,2025,2025/01/03,纪录,28,83,韓語,NaN,NaN,概覽,從場景設計到角色發展，透過演員群與導演的獨家訪談，一窺這部全球收視冠軍影集的第 2 季如何製作。
67,癲狂世代,2023,2023/10/19,剧情,125,83,西班牙語,Christopher Zalla,NaN,Think for yourself.,在一個飽受忽視、腐敗和暴力困擾的墨西哥邊境小鎮，一位沮喪的老師嘗試一種非正統的新方法來打破學...
68,防彈少年團：燃燒舞台電影版,2018,2018/11/15,"音乐,纪录",85,83,韓語,Park Jun-soo,NaN,"From the deserts to the seas, we were always t...","防彈少年團的故事將被拍成電影, 11 月 CGV 上映! 據體育東亞獨家報道, 講述防彈少年..."
69,後窗,1954,1955/06/30,"惊悚,悬疑,剧情",113,83,英語,亞弗列·希治閣,約翰·邁克爾·海耶斯,It only takes one witness to spoil the perfect...,此片被視為驚悚大師希區考克 (Alfred Hitchcock) 的經典代表作，以黑色幽默的...
70,加百列的地獄 3,2020,2020/11/19,"爱情,剧情",102,83,英語,Tosca Musk,Sylvain Reynard,概覽,一個黑暗的人帶着惡意從茱莉亞的過去回來了。加布裏埃爾有他需要分享的秘密，但擔心如果他這樣做，...
71,回到未來,1985,1985/12/14,"冒险,喜剧,科幻",116,83,英語,羅伯特·澤米吉斯,鮑勃·蓋爾,He was never in time for his classes... He was...,故事發生在 1985 年的美國。主角馬蒂·麥佛萊（Marty McFly）是一個居住在加州山...
72,野獸良民,1998,1998/10/30,剧情,119,83,英語,托尼·凱耶,大衞·麥肯納,Some legacies must end.,Derek (Edward Norton) 是一個加州年輕人，他在父親被謀殺後成為一個新納粹...
73,同級生,2016,2016/02/20,"爱情,动画",61,83,-,中村章子,中村明日美子,"Sincerely, Slowly, Falling in Love.",關於青春期中的少年們的純情故事。高中入學測驗獲得滿分成績的秀才佐條利人，以及遭受女生歡迎異性...
74,幽靈公主,1997,1997/08/14,"冒险,奇幻,动画",134,83,日語,宮崎駿,NaN,The fate of the world rests on the courage of ...,日本室町幕府時代，群雄割據，戰事連年。人民為逃避戰火，被迫棲身森林。世局動盪，令森林之神大為...
75,真愛留聲,2026,2026/06/19,"爱情,喜剧,剧情",119,83,英語,Leah McKendrick,NaN,Sometimes the universe leaves you a message.,一名年輕女子總愛留語音留言給已故的妹妹，內容坦率爆笑，而她不知道的是，留言都轉給了一個遠在他...
76,生之慾,1952,1952/10/09,剧情,143,83,日語,黑澤明,小國英雄,A big story of a little man which will grip yo...,本片為日本電影大師黑澤明早期經典代表，以淡淡的筆觸，描述老人面對死亡的心情轉變，對現代人的冷...
77,配樂大師 : ENNIO,2022,2023/06/01,"纪录,音乐,历史",156,83,意大利語,基斯比·湯納度,NaN,概覽,一代電影配樂傳奇摩利哥尼畢生為數百部電影譜曲，包括《星光伴我心》、《義薄雲天》、《獨行俠決鬥...
78,荒野機械人,2024,2024/09/17,"家庭,动画,科幻,冒险",102,83,英語,基斯·辛達斯,NaN,Discover your true nature.,夢工場近年最大突破的動畫力作 ——《荒野機械人》(THE WILD ROBOT)，環球影業發...
79,藍色恐懼,1998,2021/08/18,"动画,惊悚",82,83,日語,今敏,竹內義和,"""excuse me... who are you?""",日本傳奇級動畫大師今敏一鳴驚人之作，推出超過 20 年仍不褪色的經典！偶像團體「CHAM! ...
80,紫羅蘭永恆花園劇場版,2020,2020/10/22,"动画,剧情,奇幻,爱情",140,83,日語,石立太一,曉佳奈,概覽,從事代筆職業的她，名叫薇爾莉特艾佛加登。在讓人們傷痕累累的戰爭結束後數年，嶄新的時代來臨，世...
81,暴雨驕陽,1989,1989/06/02,剧情,129,83,英語,彼得·韋亞,託馬斯·舒爾曼,He was their inspiration. He made their lives ...,本片講述一間傳統學校的老師用反傳統的方法來教學生們詩歌、文學、生活的故事。電影不僅是主演羅賓...
82,帶來靈魂：防彈少年團演唱會電影,2019,2019/08/07,"音乐,纪录",105,83,韓語,Park Jun-soo,NaN,"Forever, we are young.",據媒體報道防彈少年團 第三部演唱會電影《Bring the Soul：The Movie》確...
83,這個殺手不太冷,1994,1997/06/26,"犯罪,剧情,动作",111,83,法語,洛·比桑,NaN,"If you want the job done right, hire a profess...",里昂（尚聯奴 飾）是紐約的頂尖職業殺手。當他的鄰居一家因毒品問題被殺害後，他無奈成為唯一倖存...
84,夜與霧,1956,1956/05/22,"纪录,历史",32,83,法語,亞倫·雷奈,讓·卡約爾,概覽,本片可説是戰後十年控訴納歲以及戰爭暴力最有力量的影片，在極為詩意、內化的基調中，娓娓道出納粹...
85,劇場版 五等分的新娘,2022,2022/10/06,"动画,喜剧,爱情",136,83,日語,神保昌登,大知慶一郎,概覽,講述為了讓「瀕臨留級」又「討厭學習」的美少女五姊妹通過學校考試畢業，主角風太郎以兼職家庭教師...
86,獻給我的前妻,2019,2019/11/08,"剧情,喜剧",94,83,西班牙語,Jorge Ulloa,Julio Pañi,概覽,這部電影講述了 21 歲的阿裏爾的故事：為籌錢挽回瀕臨破裂的戀情、與前女友重逢，他決定組建一...
87,大獨裁者,1940,1947/03/27,"喜剧,战争",125,83,英語,差利·卓別靈,NaN,Once again - the whole world laughs!,差利·卓別靈（Charles Chaplin）自導自演的第一部有聲片，此片拍攝於希特拉（Ad...
88,We All Loved Each Other So Much,1974,1974/12/21,"剧情,喜剧",125,83,意大利語,艾託尼·史寇拉,艾根諾爾·因克魯西,A many splendored thing.,Three partisans bound by a strong friendship r...
89,摩登時代,1936,1937/05/07,"喜剧,剧情,爱情",87,83,英語,差利·卓別靈,NaN,He stands alone as the greatest entertainer of...,《摩登時代》雖然是默片，但是實際上它包含聲音，比如收音機和電視機的聲音；卓別林以此來幫助 1...
90,邊境奇襲,2025,2025/02/28,"动作,冒险,惊悚",85,83,西班牙語,Chava Cartas,José Rubén Escalante Méndez,概覽,營救人質任務招來新敵人，格雷洛上尉和他率領的精銳士兵必須面對犯罪集團的伏擊。
91,莫負少年頭,1946,1946/12/20,"剧情,家庭,奇幻",131,83,英語,法蘭·基勃拉,阿爾伯特·莫里斯·哈克特,It's a wonderful laugh! It's a wonderful love!,美國 AFI 百大經典之一，喜愛經典電影的人必看佳片，一流的劇本，一流的演技。生命的價值何在...
92,制裁者：最後一擊,2026,2026/05/12,"动作,剧情,犯罪",51,83,英語,雷納爾多·馬庫斯·格林,傑瑞·康威,Hey Frank.,當法蘭克卡索尋求超越復仇的意義時，一股意想不到的力量將他拉回戰場。
93,Out of the Clear Blue Sky,2019,2019/12/24,"喜剧,剧情,音乐",112,83,西班牙語,Pepe Bojórquez,Alfredo Felix-Diaz,概覽,"Returning to Earth as an imitator, the legenda..."
94,閃亮人生,2011,2012/09/06,"剧情,喜剧",113,83,法語,奧利維埃·納卡什,埃里克·託萊達諾,一對不平凡主僕 逆轉不一樣人生,出身法國貴族世家的菲臘（法司華古薩 飾），因一次跳傘意外而幾乎全身癱瘓，只剩下情緖意識和思考...
95,紅樓金粉,1950,1950/08/10,剧情,110,83,英語,比利·懷特,查爾斯·威廉·布萊克特,A Hollywood Story: Sensational...Daring...Unfo...,比利·懷德（Billy Wilder）執導 1950 年代美國黑色電影經典之作，獲第 52 ...
96,捕風追影,2025,2025/09/11,"动作,犯罪,剧情,惊悚",142,83,漢語,楊子,NaN,He's training a new generation of law enforcer...,一夥天才盜匪劫走數億資產，卻憑藉超強反偵察能力全身而退，戲耍警方“天眼”系統。一籌莫展之際，...
97,狂沙十萬里,1968,1969/09/25,"剧情,西部",166,83,意大利語,賽爾喬·萊昂內,塞爾吉奧·多納蒂,There were three men in her life. One to take ...,義大利西部片宗師李歐尼（Sergio Leone）的傳世經典之作，繼與克林伊斯威特合作「鏢客...
98,現代啟示錄,1979,1980/03/27,"剧情,战争",153,83,英語,法蘭西斯·柯波拉,約瑟夫·康拉德,This is the end...,1968 年，特種部隊上尉班傑明·韋勒（Benjamin L.Willard）奉命前往越南「...
99,新世紀福音戰士劇場版：Air／真心為你,1997,2026/10/01,"动画,科幻,剧情,奇幻,动作",87,83,日語,庵野秀明,鶴卷和哉,The fate of destruction is also the joy of reb...,本作是由 TV 版第 25 話與最終話的重新製作所構成的兩話內容。第 25 話〈Air〉：在...

In [17]:
# 数据查看 --> head , tail , describe , info , shape , columns
df.head(10)
df.tail(10)
df.describe() # 显示数据的统计信息
df.info() # 显示数据信息（列名，非空技术，数据类型等）
df.shape # 维度
df.columns # 显示列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   电影名     100 non-null    object
 1   年份      100 non-null    int64
 2   上映时间    100 non-null    object
 3   类型      100 non-null    object
 4   时长      100 non-null    int64
 5   评分      100 non-null    int64
 6   语言      100 non-null    object
 7   导演      99 non-null     object
 8   作者      76 non-null     object
 9   口号      100 non-null    object
 10  描述      100 non-null    object
 11  有效时长    100 non-null    int64
dtypes: int64(4), object(8)
memory usage: 9.5+ KB

Index(['电影名', '年份', '上映时间', '类型', '时长', '评分', '语言', '导演', '作者', '口号', '描述',
       '有效时长'],
      dtype='object')

In [26]:
# 数据选择
# 1. 选择列
# 1.1 单列
# df['电影名']
#
# # 1。2 多列
# df[['电影名','导演']]
#
# # 2. 选择行 - iloc , loc
# # 2.1 iloc --> 基于行号选择行，常见语法：df.iloc[start:stop:step]
# df.iloc[0:10:1]
# df.iloc[0:10]
#
# # 2.2 loc ---> 基于索引选择行（包含结束位置），语法：df.loc[start:stop:strp]
# df.loc[1:10]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述,有效时长
1,Avatar Aang: The Last Airbender,2026,2026/07/24,"动画,冒险,奇幻,动作",99,91,-,Tim Hedrick,勞倫·蒙哥馬利,The legacy reawakens.,"Avatar Aang, the world's last Airbender, learn...",79
2,奇幻變身大冒險,2026,2026/05/01,"冒险,动画,家庭,奇幻",102,89,英語,內森·格雷諾,Robert Snow,Transform your destiny.,林地小動物和大鳥突然互換了身體，只好彼此合作，共同面對一生最瘋狂的冒險。,82
3,Accidental Partners,2026,2026/03/12,"喜剧,爱情",110,88,西班牙語,Ihtzi Hurtado,Miguel García Moreno,概覽,Two women discover they were both scammed by t...,90
4,鬼滅之刃劇場版 無限城篇 第一章 猗窩座再襲,2025,2025/08/14,"动画,动作,奇幻",155,88,日語,外崎春雄,吾峠呼世晴,It's time to have some fun.,為了讓變成鬼的妹妹禰豆子變回人類，加入鬼殺隊的灶門炭治郎，一路上與不同的「柱」成為同伴，並肩...,135
5,夜巡毒梟,2026,2026/08/21,"犯罪,动作,惊悚",91,88,西班牙語,Chava Cartas,Bernardo Esquinca,概覽,兩位墨西哥員警不幸得罪一名殘忍的毒梟後，必須拼命撐過值勤的最後幾小時。這部犯罪劇情片改編自真...,71
6,月黑高飛,1994,1995/10/26,"剧情,犯罪",142,87,英語,法蘭·達拉本特,史提芬·京,Fear can hold you prisoner. Hope can set you f...,1947 年，一位年輕的波特蘭銀行家安迪·杜佛蘭（添·羅賓斯飾）被指控殺死其妻子與其情夫，分...,122
7,教父,1972,1980/01/24,"剧情,犯罪",175,87,英語,法蘭西斯·柯波拉,馬里奧·普佐,An offer you can't refuse.,電影描述西西里的柯里安大家族於美國掘起，辛苦掙扎奮鬥成為黑幫教父，最後引起權力鬥爭，甚至家族...,155
8,末日聖母號,2026,2026/03/19,"科幻,冒险",157,86,英語,菲力洛迪文,克里斯·米勒,Believe in the Hail Mary.,科學老師 Ryland Grace（賴恩高斯寧 飾）在一艘距離地球數光年遠的太空船上醒來，隨...,137
9,米高積遜,2026,2026/04/22,"音乐,剧情",128,86,英語,安東尼·福奎阿,約翰·洛根,Discover the making of a king.,《米高積遜》聚焦他的音樂成就，更深入描寫他舞台之外的人生軌跡：從幼年被發掘成為 Jackso...,108
10,年少心事,2024,2024/09/14,"剧情,爱情",99,86,荷蘭語,安東尼·沙特曼,NaN,概覽,在學期間，13 歲的 Elias 與來自布魯塞爾的 14 歲新鄰居 Alexander 成為...,79

In [48]:
# 数据过滤 ---> df[filter]
# 1.获取评分 > 90
# df[df['评分'] > 90]

# 2.获取类别为 科幻或者动作 的电影 ？？？

# 3.获取评分在80-90之间 ---> 默认包含边界
df[df['评分'].between(80,90)]

# 4.获取时长 > 120 并且评分 > 85
df[(df['评分'] >= 85) & (df['时长'] >= 120)]

# 5.获取年份2025/2026 并且 评分在80-99之间
df[(df['年份'].isin([2025,2026])) & (df['评分'].between(80,99))]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,口号,描述,有效时长
0,蝙蝠俠 騎士殞落（一）：騎士殞落,2026,2026/08/25,"动画,动作,冒险,科幻",79,92,英語,比爾·芬格,鮑勃·凱恩,概覽,"Arkham Asylum has been destroyed, and all its ...",59
1,Avatar Aang: The Last Airbender,2026,2026/07/24,"动画,冒险,奇幻,动作",99,91,-,Tim Hedrick,勞倫·蒙哥馬利,The legacy reawakens.,"Avatar Aang, the world's last Airbender, learn...",79
2,奇幻變身大冒險,2026,2026/05/01,"冒险,动画,家庭,奇幻",102,89,英語,內森·格雷諾,Robert Snow,Transform your destiny.,林地小動物和大鳥突然互換了身體，只好彼此合作，共同面對一生最瘋狂的冒險。,82
3,Accidental Partners,2026,2026/03/12,"喜剧,爱情",110,88,西班牙語,Ihtzi Hurtado,Miguel García Moreno,概覽,Two women discover they were both scammed by t...,90
4,鬼滅之刃劇場版 無限城篇 第一章 猗窩座再襲,2025,2025/08/14,"动画,动作,奇幻",155,88,日語,外崎春雄,吾峠呼世晴,It's time to have some fun.,為了讓變成鬼的妹妹禰豆子變回人類，加入鬼殺隊的灶門炭治郎，一路上與不同的「柱」成為同伴，並肩...,135
5,夜巡毒梟,2026,2026/08/21,"犯罪,动作,惊悚",91,88,西班牙語,Chava Cartas,Bernardo Esquinca,概覽,兩位墨西哥員警不幸得罪一名殘忍的毒梟後，必須拼命撐過值勤的最後幾小時。這部犯罪劇情片改編自真...,71
8,末日聖母號,2026,2026/03/19,"科幻,冒险",157,86,英語,菲力洛迪文,克里斯·米勒,Believe in the Hail Mary.,科學老師 Ryland Grace（賴恩高斯寧 飾）在一艘距離地球數光年遠的太空船上醒來，隨...,137
9,米高積遜,2026,2026/04/22,"音乐,剧情",128,86,英語,安東尼·福奎阿,約翰·洛根,Discover the making of a king.,《米高積遜》聚焦他的音樂成就，更深入描寫他舞台之外的人生軌跡：從幼年被發掘成為 Jackso...,108
14,鏈鋸人 - 劇場版：蕾潔篇,2025,2025/09/25,"动画,动作,爱情,奇幻",100,86,日語,吉原達矢,瀨古浩司,"Lost Love, Flower, Chainsaw.",主角澱治曾是黑幫的惡魔獵人，試圖償還父母留下的債務。後來，他被黑幫背叛、殺害，就在瀕死之際，...,80
42,明亮燦爛的你,2026,2026/05/08,"剧情,悬疑",114,84,英語,奧利維亞·紐曼,約翰·惠廷頓,Brighter together.,這部動人的劇情片改編自暢銷小說，描述一名寡婦在小鎮水族館值夜班，和一隻聰明的章魚及一個迷茫的...,94
48,Protector,2026,2026/03/06,"动作,惊悚",90,84,-,阿德裏安·格魯伯格,Mun-Bong Seub,Never get between a mother and her child.,Nikki's life is shattered when her daughter is...,70
61,反斗奇兵 5,2026,2026/06/18,"动画,家庭,喜剧,冒险",102,84,英語,安德魯·斯坦頓,Kenna Harris,It's on.,一班玩具朋友面對「莉莉平板」（Lily Pad）如臨大敵，嚇到騰騰震，誓要與現今小朋友最沉迷...,82
66,魷魚遊戲：第 2 季：製作特輯,2025,2025/01/03,纪录,28,83,韓語,NaN,NaN,概覽,從場景設計到角色發展，透過演員群與導演的獨家訪談，一窺這部全球收視冠軍影集的第 2 季如何製作。,8
75,真愛留聲,2026,2026/06/19,"爱情,喜剧,剧情",119,83,英語,Leah McKendrick,NaN,Sometimes the universe leaves you a message.,一名年輕女子總愛留語音留言給已故的妹妹，內容坦率爆笑，而她不知道的是，留言都轉給了一個遠在他...,99
90,邊境奇襲,2025,2025/02/28,"动作,冒险,惊悚",85,83,西班牙語,Chava Cartas,José Rubén Escalante Méndez,概覽,營救人質任務招來新敵人，格雷洛上尉和他率領的精銳士兵必須面對犯罪集團的伏擊。,65
92,制裁者：最後一擊,2026,2026/05/12,"动作,剧情,犯罪",51,83,英語,雷納爾多·馬庫斯·格林,傑瑞·康威,Hey Frank.,當法蘭克卡索尋求超越復仇的意義時，一股意想不到的力量將他拉回戰場。,31
96,捕風追影,2025,2025/09/11,"动作,犯罪,剧情,惊悚",142,83,漢語,楊子,NaN,He's training a new generation of law enforcer...,一夥天才盜匪劫走數億資產，卻憑藉超強反偵察能力全身而退，戲耍警方“天眼”系統。一籌莫展之際，...,122